### PR TITLE
Fix a few issues and use feaLib

### PR DESCRIPTION
**Pull request by adrientetar**
r? @jamesgk

### CODE REVIEW

**Comment by adrientetar** [comment]
FYI cc @behdad @brawer

**Comment by jamesgk** [comment]
To address this issue from https://github.com/jamesgk/ufo2ft/pull/6#issuecomment-164142104:

> `rec.string = nameVals[nameId].encode(rec.getEncoding(), "strict")` should probably call `normalizeStringForPostscript` before encoding, I had non-ASCII characters in my font info (ok, maybe I shouldn't(?)) and it crashed ufo2ft.

I had this diff locally:

```diff
--- a/Lib/ufo2ft/outlineOTF.py
+++ b/Lib/ufo2ft/outlineOTF.py
@@ -267,12 +267,13 @@ class OutlineCompiler(object):
         name.names = []
         for ids in [(1, 0, 0x0), (3, 1, 0x409)]:
             for nameId in sorted(nameVals.keys()):
-                if not nameVals[nameId]:
+                nameVal = normalizeStringForPostscript(nameVals[nameId])
+                if not nameVal:
                     continue
                 rec = NameRecord()
                 rec.platformID, rec.platEncID, rec.langID = ids
                 rec.nameID = int(nameId)
-                rec.string = nameVals[nameId].encode(
+                rec.string = nameVal.encode(
                     rec.getEncoding(), "strict")
                 name.names.append(rec)
```

Do you want to add it to this pull request? Or is it still an issue?

**Comment by adrientetar** [comment]
I will thanks, I think it should use normalizeNameForPostscript in the name table though.

**Comment by adrientetar** [comment]
Okay, looking at the otspec it seems only name id 6 (postscript font name) should be normalized for postscript. 
For the rest it could be done by just using "ignore" instead of "strict" in the encode() call which will drop unencodable chars. But that may introduce discrepencies between win and mac strings if there is characters that are encodable in the mac encoding but not in the windows one or vice-versa. I don't know if that is a problem.

**Comment by anthrotype** [comment]
I believe we should only normalizeStringForPostscript the nameID=6, and let the other name records use "strict" and raise UnicodeEncodeError when it fails. Or if you like raise a custom exception with an error message pointing to the specific name record which could not be encoded. This would be better than simply having unencodeable characters ignored, I think.

**Comment by adrientetar** [comment]
I think it should be ufo2ft's job to encode strings in a way that honors ot requirements, not caller's or file author's (also, why ask caller for a compatible string when it's ufo2ft that decides which name tables to generate and the encoding in the end depends on that). Plus normalizeStringForPostscript and ufo2fdk's winStr and macStr functions that were used for this do normalize and drop chars.

**Comment by anthrotype** [comment]
Ok, I see. But at least a warning message should be printed in case characters are dropped.

**Comment by brawer** [comment]
When a name cannot be encoded in some legacy Mac encoding, how about emitting it with platformID=0 (Unicode), platformSpecificID=4 (Unicode v2.0 and later), and languageID=index into an [ltag table](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6ltag.html)? FWIW, there’s also some [code in OpenType.js for building ‘name’ and ‘ltag’ tables given a dictionary keyed by IETF BCP-47 language tags](https://github.com/nodebox/opentype.js/blob/master/src/tables/name.js#L763).

**Comment by behdad** [comment]
In my opinion we should emit one and only one encoding per name string / language pair.

If text contains non-BMP chars, encode as platformID=3, encodingID=10.  Otherwise, encode as platformID=3, encodingID=1.

A small optimization would be, if it's all ASCII, encode as platformID=1, encodingID=0. (MacRoman)  Need to test that this is supported on Windows.  Or just forget this for now.

Windows names are fully supported on Mac, so all the "for portability" reasoning is moot IMO.

**Comment by behdad** [comment]
> When a name cannot be encoded in some legacy Mac encoding, how about emitting it with platformID=0 (Unicode), platformSpecificID=4 (Unicode v2.0 and later), and languageID=index into an ltag table? FWIW, there’s also some code in OpenType.js for building ‘name’ and ‘ltag’ tables given a dictionary keyed by IETF BCP-47 language tags.

BTW, we need to write that proposal for using ltag with non-Mac encodings.

**Comment by adrientetar** [comment]
> A small optimization would be, if it's all ASCII, encode as platformID=1, encodingID=0. (MacRoman) Need to test that this is supported on Windows. Or just forget this for now.

I recall @davelab6 said that platformID=1 names were only used on Mac OS 9 and that now they can be dropped in favor of Windows names only.

**Comment by adrientetar** [comment]
That was in adobe-type-tools/afdko#58, consequently these names were dropped from mandatory include in the AFDKO. 
I think we can just stop generating them here.

**Comment by behdad** [comment]
> That was in adobe-type-tools/afdko#58, consequently these names were dropped from mandatory include in the AFDKO.
> I think we can just stop generating them here.

I was suggesting using them in place of Windows names if the name is ASCII-only.  MacRoman is encoded as 1-byte per character, whereas Windows names are 2-bytes.

**Comment by adrientetar** [comment]
> I was suggesting using them in place of Windows names if the name is ASCII-only. MacRoman is encoded as 1-byte per character, whereas Windows names are 2-bytes.

Okay. I don't think that Windows and other non-Mac platforms will take the macroman attributes, I haven't tested though.

**Comment by adrientetar** [comment]
@miguelsousa Do you by chance know if it's acceptable to put name attributes only in MacRoman encoding?

**Comment by miguelsousa** [comment]
> Do you by chance know if it's acceptable to put name attributes in MacRoman encoding only?

I don't, but I think @kenlunde has experimented using Windows names only.

**Comment by kenlunde** [comment]
@adrientetar I would think that the opposite would be preferred. OS X uses the Windows (de facto Unicode) 'name' table strings, if they exist. MacRoman 'name' table strings are no longer necessary.

**Comment by kenlunde** [comment]
I recently wrote a [CJK Type Blog article](https://blogs.adobe.com/CCJKType/2015/11/whats-in-a-name-table.html) about this.

**Comment by davelab6** [comment]
The reason Behdad suggested this is that it will result in a smaller
filesize.

**Comment by kenlunde** [comment]
My personal opinion is that using Unicode, which is the de facto way to represent digital text in modern environments, should trump any size savings that can be gained by using a legacy encoding. It's nice to reduce file sizes, but it doesn't seem like the right thing to do in this case. In fact, my understanding is that the Windows (aka Unicode) strings are the only required ones. The Macintosh strings are optional.

**Comment by behdad** [comment]
Let's just say we all understand and agree that if Windows names are provided, then MacRoman is not needed.  But that was not the question.  I still appreciate the answer to my original question if someone knows.

A while ago we dropped MacRoman support in name tables from fontconfig, but we brought it back, because Apple Color Emoji only has MacRoman for English family name.

**Comment by kenlunde** [comment]
@behdad I would consider the lack of Unicode 'name' table strings to be a bug. Has anyone contacted Apple?

**Comment by adrientetar** [comment]
Maybe it's a way for Apple to have the font working only on their platform?

**Comment by kenlunde** [comment]
@adrientetar Dollars to donuts that it was an oversight, hence my suggestion to treat it as a bug.

**Comment by adrientetar** [comment]
@jamesgk any more opinions?

**Comment by jamesgk** [comment]
This looks good to me. However, I'm hesitant to merge it until my open issues over at FontTools have been closed. So far I haven't gotten any font to compile successfully on this branch.

**Comment by jamesgk** [comment]
Well, this has other useful stuff, so let's just merge. I'll open a temporary afdko branch for now.

**Pull request merged**
